### ISSUE TITLE
Specs still not passing on a standard setup

### ISSUE THREAD

**Issue by urkle** [HookOps/hubstaff-ruby#23]
1) specs should **never** depend on the environment.
  - remove ALL references to ENV in side of the spec/ folder and replace them with const values.. e.g.  app_token = 'APP_TOKEN'  auth_token = 'AUTH_TOKEN'
2) specs should **not** use modules to define them
  - instead just reference the full calss..  e.g.   `RSpec.describe Hubstaff::Client do`

As it stands right now, 94 our of 98 test fail because they are depending on the local environment.

**Comment by urkle** [comment]
Also remove the re_record_interval attribute to all of the VCR setups.

**Comment by kandalf** [comment]
Hi @urkle! Is this the only issue preventing a new release?
I'm asking because I'd like to use this gem, but the released version has a couple of issues:

* It's requiring `dotenv` in `lib/hubstaff.rb`
<img width="643" alt="image" src="https://user-images.githubusercontent.com/43977/28212670-e85e3a96-6878-11e7-8440-32d29d66302e.png">

* It's lacking the ability of assigning the auth token to the client, forcing the need of using the email/password to authenticate

Both of those issues are kind of easy to overcome, but also I see both of the issues are resolved in the master branch. It'd be nice to have a new release without the need of workarounds.

If this is the only thing preventing a new release, I could help you with this to speed up the new version.

Please, let me know what you think.

Cheers!

**Comment by urkle** [comment]
@kandalf we are working with the developers who created this gem to fix all the issues so we can pull this over to NetsoftHoldings and actually release a proper gem.

And what "released" version of the gem are you referring to? there should be no released version of this gem at all.

**Comment by kandalf** [comment]
@urkle Great, do you have any ballpark estimation? We could go with a local version in the meanwhile, knowing that it is active and the release is in process.

Rubygems.org has version [`0.0.1`](https://rubygems.org/gems/hubstaff-ruby). It seems to be created with an old github username, but it still redirects here.
